name: build container
on: push
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          context: .
          push: true
          load: false
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_type  }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Inspect
        run: |
          docker pull ghcr.io/${{ github.repository }}:${{ github.ref_type  }}
          docker image inspect ghcr.io/${{ github.repository }}:${{ github.ref_type  }}
  # tests:
  #   needs: build-container
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Run Ecal
  #       run: |
  #         docker pull ghcr.io/${{ github.repository }}:${{ github.ref_type  }}
  #         docker run -itd --name g4runtime -v /home/runner/work/g4bench/g4bench:/home/runner/work/g4bench/g4bench ghcr.io/${{ github.repository }}:${{ github.ref_type  }}
  #         docker exec -w /home/runner/work/g4bench/g4bench -e NOG4VERSION=1 g4runtime tests/ci/test_ecal.sh
  #     - name: Run Hcal
  #       run: |
  #         docker pull ghcr.io/${{ github.repository }}:${{ github.ref_type  }}
  #         docker run -itd --name g4runtime -v /home/runner/work/g4bench/g4bench:/home/runner/work/g4bench/g4bench ghcr.io/${{ github.repository }}:${{ github.ref_type  }}
  #         docker exec -w /home/runner/work/g4bench/g4bench -e NOG4VERSION=1 g4runtime tests/ci/test_hcal.sh
  #     - name: Run Vgeo_x18
  #       run: |
  #         docker pull ghcr.io/${{ github.repository }}:${{ github.ref_type  }}
  #         docker run -itd --name g4runtime -v /home/runner/work/g4bench/g4bench:/home/runner/work/g4bench/g4bench ghcr.io/${{ github.repository }}:${{ github.ref_type  }}
  #         docker exec -w /home/runner/work/g4bench/g4bench -e NOG4VERSION=1 g4runtime tests/ci/test_vgeo_x18.sh

