# GitHub Actions for CI

name: Test Ecal

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run:
    needs: build-container
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Build and Run Ecal
        run: |
          docker pull ghcr.io/${{ github.repository }}:${{ github.ref_type  }}
          docker run -itd --name g4runtime -v /home/runner/work/g4bench/g4bench:/home/runner/work/g4bench/g4bench ghcr.io/${{ github.repository }}:${{ github.ref_type  }}
          docker exec -w /home/runner/work/g4bench/g4bench -e NOG4VERSION=1 g4runtime tests/ci/test_ecal.sh
